"use server";

import { createClient } from "@/lib/supabase/server";
import { sendInvitesSchema, type SendInvitesInput } from "@/lib/schemas/invite";
import { resend } from "@/lib/email/resend";
import { TripInviteEmail } from "@/lib/email/templates/trip-invite";

export async function sendInvites(input: SendInvitesInput) {
  const parsed = sendInvitesSchema.safeParse(input);
  if (!parsed.success) {
    return { error: parsed.error.flatten().fieldErrors };
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return { error: { _form: ["Not authenticated"] } };
  }

  // Verify user is host/co-host
  const { data: membership } = await supabase
    .from("trip_members")
    .select("role")
    .eq("trip_id", parsed.data.trip_id)
    .eq("user_id", user.id)
    .single();

  if (!membership || !["host", "co-host"].includes(membership.role)) {
    return { error: { _form: ["Only hosts can invite guests"] } };
  }

  // Fetch trip name + dates for email
  const { data: trip } = await supabase
    .from("trips")
    .select("name, starts_on, ends_on")
    .eq("id", parsed.data.trip_id)
    .single();

  if (!trip) {
    return { error: { _form: ["Trip not found"] } };
  }

  const { data: hostUser } = await supabase
    .from("users")
    .select("display_name")
    .eq("id", user.id)
    .single();

  const hostName = hostUser?.display_name || user.email || "Your host";
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

  const formatDate = (d: string | null) =>
    d
      ? new Date(d + "T00:00:00").toLocaleDateString("en-US", {
          month: "short",
          day: "numeric",
        })
      : null;

  const start = formatDate(trip.starts_on);
  const end = formatDate(trip.ends_on);
  const tripDates =
    start && end
      ? `${start} – ${end}`
      : start
        ? `Starting ${start}`
        : "Dates TBD";

  const results: { email: string; success: boolean; error?: string }[] = [];

  for (const email of parsed.data.emails) {
    // Check if already invited (not consumed)
    const { data: existing } = await supabase
      .from("trip_invites")
      .select("id")
      .eq("trip_id", parsed.data.trip_id)
      .eq("email", email.toLowerCase())
      .is("consumed_at", null)
      .single();

    if (existing) {
      results.push({ email, success: false, error: "Already invited" });
      continue;
    }

    // Check if already a member
    const { data: existingMember } = await supabase
      .from("trip_members")
      .select("id")
      .eq("trip_id", parsed.data.trip_id)
      .eq("invited_email", email.toLowerCase())
      .single();

    if (existingMember) {
      results.push({ email, success: false, error: "Already a member" });
      continue;
    }

    // Create invite row (token auto-generated by DB default)
    const { data: invite, error: inviteError } = await supabase
      .from("trip_invites")
      .insert({
        trip_id: parsed.data.trip_id,
        email: email.toLowerCase(),
      })
      .select("token")
      .single();

    if (inviteError || !invite) {
      results.push({
        email,
        success: false,
        error: inviteError?.message || "Failed to create invite",
      });
      continue;
    }

    // Send email via Resend
    const viewUrl = `${baseUrl}/trip/${invite.token}`;

    try {
      await resend.emails.send({
        from: "Roost <noreply@roost.app>",
        to: email,
        subject: `${hostName} invited you to ${trip.name}`,
        react: TripInviteEmail({
          tripName: trip.name,
          hostName,
          tripDates,
          viewUrl,
        }),
      });
      results.push({ email, success: true });
    } catch (emailError) {
      results.push({
        email,
        success: false,
        error:
          emailError instanceof Error ? emailError.message : "Email send failed",
      });
    }
  }

  return { data: results };
}
